---
resources:
  - name: tutorial
    type: git
    source:
      uri: https://github.com/matthewbga/concourse-tutorial.git
      branch: master

  - name: concourse-builder-image
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/concourse-builder

jobs:
  - name: publish
    public: true
    plan:
      - get: tutorial
      - put: concourse-builder-image
        params:
          build: tutorial/tutorials/miscellaneous/docker-images/docker
      - task: run
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((docker-hub-username))/concourse-builder
          run:
            path: /bin/hello-world
            args: []
          params:
            NAME: ((docker-hub-username))
